/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.model.HoaDon;
import com.raven.service.HoaDonService;
import com.raven.service.impl.HoaDonImpl;
import com.raven.uitlities.DBConnect;
import com.raven.view.ViewHoaDon;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
import static org.apache.poi.hssf.usermodel.HeaderFooter.file;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author LENOVO
 */
public class Form_HoaDon extends javax.swing.JPanel {

    HoaDonService hdSer = new HoaDonImpl();
    List<HoaDon> list = new ArrayList<>();
    public static DBConnect conn;

    /**
     * Creates new form Form_HoaDon
     */
    public Form_HoaDon() {
        initComponents();
        list = hdSer.getAll();
        loadTable(list);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        txtTimKiemNgay = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtMaSP = new javax.swing.JTextField();
        txtDonGia = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtNgayThanhToan = new com.toedter.calendar.JDateChooser();
        cboTrangThai = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTenXe = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtMauSac = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtXuatXu = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtSoTienGiam = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnLocDate = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtTim = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        cboLocTrangThai = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnHienThi = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Hóa Đơn", "Mã Nhân Viên", "Tên Nhân Viên", "Tên Khách Hàng", "Mã Sản Phẩm", "Tên Xe", "Màu Sắc", "Xuất Xứ", "Đơn Giá", "Số Lượng", "Số Tiền Giảm", "Tổng Tiền", "Ngày Thanh Toán", "Trạng Thái", "Note"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tìm kiếm hóa đơn");

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel7.setText("Ngày Thanh Toán");

        jLabel9.setText("Tổng Tiền");

        jLabel10.setText("Số Tiền Giảm");

        jLabel14.setText("Trạng Thái");

        jLabel2.setText("Mã Hóa Đơn");

        jLabel3.setText("Mã Sản Phẩm");

        jLabel4.setText("Tên Nhân Viên");

        jLabel5.setText("Tên Khách Hàng");

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã Thanh Toán", "Chưa Thanh Toán" }));

        jLabel16.setText("Note");

        jScrollPane2.setViewportView(txtNote);

        jLabel12.setText("Mã Nhân Viên");

        jLabel13.setText("Tên Xe");

        jLabel17.setText("Màu sắc");

        jLabel18.setText("Xuất Xứ");

        jLabel19.setText("Số Lượng");

        jLabel20.setText("Đơn Giá");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(txtMaHD)
                            .addComponent(txtTenNV)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTenXe, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMauSac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)))))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(jLabel19)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDonGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtSoTienGiam, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTongTien))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jLabel12)
                                .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtXuatXu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(txtSoTienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNgayThanhToan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("DANH SÁCH HÓA ĐƠN");

        btnLocDate.setText("Lọc");
        btnLocDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocDateActionPerformed(evt);
            }
        });

        jButton5.setText("EXPORT TO EXCEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED), "TÌM KIẾM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N

        jLabel15.setText("Nhập mã Hóa đơn cần tìm");

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        jButton6.setText("Tìm kiếm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        cboLocTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã Thanh Toán", "Chưa Thanh Toán" }));
        cboLocTrangThai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLocTrangThaiItemStateChanged(evt);
            }
        });

        jLabel11.setText("Trạng Thái");

        btnHienThi.setText("Hiển Thị");
        btnHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 255, 204));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.png"))); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHienThi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(cboLocTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel15)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton6)
                .addComponent(cboLocTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel11)
                .addComponent(btnHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnDelete))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimKiemNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLocDate)
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(58, 58, 58)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiemNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(btnLocDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
public void loadTable(List<HoaDon> lst) {
        DefaultTableModel dtm = (DefaultTableModel) tblHoaDon.getModel();
        dtm.setRowCount(0);
        for (HoaDon hd : lst) {
            Object rowData[] = {
                hd.getMaHD(),
                hd.getMaNV(),
                hd.getTenNV(),
                hd.getTenKH(),
                hd.getMaSP(),
                hd.getTenXe(),
                hd.getMauSac(),
                hd.getXuatXu(),
                hd.getDonGia(),
                hd.getSoLuong(),
                hd.getSoTienGiam(),
                hd.getTongTien(),
                hd.getNgayThanhToan(),
                hd.getTrangThai() == 0 ? "Đã Thanh Toán" : "Chưa Thanh Toán",
                hd.getNote()

            };
            dtm.addRow(rowData);
        }
    }

    public void XuatHoaDon(String idhd) {
        try {
            Hashtable map = new Hashtable();
            map.put("maHD", idhd);//
            JasperReport rpt = JasperCompileManager.compileReport("src\\com\\raven\\view\\XuatHoaDon.jrxml");
            //map.put("MaHoaDon", cbbMaHoaDonBangHDCT.getSelectedItem());
            java.sql.Connection con = DBConnect.getConnection();
            //  java.sql.Connection connection = null;
            JasperPrint p = JasperFillManager.fillReport(rpt, map, con);
            JasperViewer.viewReport(p, false);
        } catch (JRException ex) {
            Logger.getLogger(ViewHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:

        int row = tblHoaDon.getSelectedRow();
        if (row == -1) {
            return;
        }

        //
        String maHD = tblHoaDon.getValueAt(row, 0).toString();
        int n = JOptionPane.showConfirmDialog(
                null,
                "Bạn có muốn xuất PDF HÓA ĐƠN không ?",
                "HÓA ĐƠN",
                JOptionPane.YES_NO_OPTION);
        if (n == 0) {
            XuatHoaDon(maHD);
        } else {

            String maNV = tblHoaDon.getValueAt(row, 1).toString();
            String tenNV = tblHoaDon.getValueAt(row, 2).toString();
            String tenKH = tblHoaDon.getValueAt(row, 3).toString();
            String maSP = tblHoaDon.getValueAt(row, 4).toString();
            String tenXe = tblHoaDon.getValueAt(row, 5).toString();
            String mauSac = tblHoaDon.getValueAt(row, 6).toString();
            String xuatXu = tblHoaDon.getValueAt(row, 7).toString();
            String donGia = tblHoaDon.getValueAt(row, 8).toString();
            String soLuong = tblHoaDon.getValueAt(row, 9).toString();
            String soTienGiam = tblHoaDon.getValueAt(row, 10).toString();
            String tongTien = tblHoaDon.getValueAt(row, 11).toString();
            String trangThai = tblHoaDon.getValueAt(row, 13).toString();
            String note = tblHoaDon.getValueAt(row, 14).toString();

            try {
                tblHoaDon.getSelectedRow();
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tblHoaDon.getValueAt(row, 12).toString());
                txtNgayThanhToan.setDate(date);
            } catch (Exception e) {

            }
            txtMaHD.setText(maHD);
            txtMaNV.setText(maNV);
            txtTenNV.setText(tenNV);
            txtTenKH.setText(tenKH);
            txtMaSP.setText(maSP);
            txtTenXe.setText(tenXe);
            txtMauSac.setText(mauSac);
            txtXuatXu.setText(xuatXu);
            txtDonGia.setText(donGia);
            txtSoLuong.setText(soLuong);
            txtSoTienGiam.setText(soTienGiam);
            txtTongTien.setText(tongTien);
            txtNote.setText(note);

            if (trangThai == "Đã Thanh Toán") {
                cboTrangThai.setSelectedIndex(0);
            } else {
                cboTrangThai.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiActionPerformed
        // TODO add your handling code here:
        list = hdSer.getAll();
        loadTable(list);
    }//GEN-LAST:event_btnHienThiActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int trangThai = 0;
        if (cboTrangThai.getSelectedItem().toString().equalsIgnoreCase("Đã Thanh Toán")) {
            trangThai = 1;
        }
        int row = tblHoaDon.getSelectedRow();
        JOptionPane.showMessageDialog(this, hdSer.delete(tblHoaDon.getValueAt(row, 0).toString()));
        list = hdSer.getAll();
        loadTable(list);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLocDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocDateActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFM = new SimpleDateFormat("YYYY-MM-dd");
        String ngayThanhToan = dateFM.format(txtTimKiemNgay.getDate());
        List<HoaDon> lst1 = hdSer.getSearchThoiGian(ngayThanhToan);

        if (lst1.size() == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy");
            return;
        } else {
            loadTable(lst1);
            JOptionPane.showMessageDialog(this, "Đã tìm thấy");
            return;
        }
    }//GEN-LAST:event_btnLocDateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            XSSFWorkbook wb = new XSSFWorkbook();
            XSSFSheet sheet = wb.createSheet("danhsach");
            XSSFRow row = null;
            Cell cell = null;
            row = sheet.createRow(3);
            cell = row.createCell(0, CellType.STRING);
            cell.setCellValue("STT");
            cell = row.createCell(1, CellType.STRING);
            cell.setCellValue("MÃ HÓA ĐƠN");
            cell = row.createCell(2, CellType.STRING);
            cell.setCellValue("MÃ NHÂN VIÊN ");
            cell = row.createCell(3, CellType.STRING);
            cell.setCellValue("TÊN NHÂN VIÊN");
            cell = row.createCell(4, CellType.STRING);
            cell.setCellValue("TÊN KHÁCH HÀNG");
            cell = row.createCell(5, CellType.STRING);
            cell.setCellValue("MÃ SẢN PHẨM");
            cell = row.createCell(6, CellType.STRING);
            cell.setCellValue("TÊN XE");
            cell = row.createCell(7, CellType.STRING);
            cell.setCellValue("MÀU SẮC");
            cell = row.createCell(8, CellType.STRING);
            cell.setCellValue("XUẤT XỨ");
            cell = row.createCell(9, CellType.STRING);
            cell.setCellValue("ĐƠN GIÁ");
            cell = row.createCell(10, CellType.STRING);
            cell.setCellValue("SỐ LƯỢNG");
            cell = row.createCell(11, CellType.STRING);
            cell.setCellValue("SỐ TIỀN GIẢM");
            cell = row.createCell(12, CellType.STRING);
            cell.setCellValue("TỔNG TIỀN");
            cell = row.createCell(13, CellType.STRING);
            cell.setCellValue("NGÀY THANH TOÁN");
            cell = row.createCell(14, CellType.STRING);
            cell.setCellValue("TRẠNG THÁI");
            cell = row.createCell(15, CellType.STRING);
            cell.setCellValue("NOTE");
            System.out.println(list);
            for (int i = 0; i < list.size(); i++) {
                row = sheet.createRow(4 + i);
                cell = row.createCell(0, CellType.NUMERIC);
                cell.setCellValue(i + 1);
                cell = row.createCell(1, CellType.STRING);
                cell.setCellValue(list.get(i).getMaHD());
                cell = row.createCell(2, CellType.STRING);
                cell.setCellValue(list.get(i).getMaNV());
                cell = row.createCell(3, CellType.STRING);
                cell.setCellValue(list.get(i).getTenNV());
                cell = row.createCell(4, CellType.STRING);
                cell.setCellValue(list.get(i).getTenKH());
                cell = row.createCell(5, CellType.STRING);
                cell.setCellValue(list.get(i).getMaSP());
                cell = row.createCell(6, CellType.STRING);
                cell.setCellValue(list.get(i).getTenXe());
                cell = row.createCell(7, CellType.STRING);
                cell.setCellValue(list.get(i).getMauSac());
                cell = row.createCell(8, CellType.STRING);
                cell.setCellValue(list.get(i).getXuatXu());
                cell = row.createCell(9, CellType.STRING);
                cell.setCellValue(list.get(i).getDonGia());
                cell = row.createCell(10, CellType.STRING);
                cell.setCellValue(list.get(i).getSoLuong());
                cell = row.createCell(11, CellType.STRING);
                cell.setCellValue(list.get(i).getSoTienGiam());
                cell = row.createCell(12, CellType.STRING);
                cell.setCellValue(list.get(i).getTongTien());
                cell = row.createCell(13, CellType.STRING);
                cell.setCellValue(list.get(i).getNgayThanhToan());
                cell = row.createCell(14, CellType.STRING);
                cell.setCellValue(list.get(i).getTrangThai() == 1 ? "Đã Thanh Toán" : "Chưa Thanh Toán");
                cell = row.createCell(15, CellType.STRING);
                cell.setCellValue(list.get(i).getNote());

            }
            JFileChooser fileChooser = new JFileChooser("");
            int x = fileChooser.showSaveDialog(this);
            FileOutputStream fos = null;
            File files = fileChooser.getSelectedFile();
            try {
                fos = new FileOutputStream(files + ".xlsx");
                wb.write(fos);
                fos.close();
                JOptionPane.showMessageDialog(this, "Xuất true");
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String ma = txtTim.getText().trim();
        List<HoaDon> lst = hdSer.getOneSP(ma);
        if (ma.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Nhập sản phẩm cần tìm");
            return;
        }
        if (lst.size() == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy");
            return;
        } else {
            loadTable(lst);
            JOptionPane.showMessageDialog(this, "Đã tìm thấy");
            return;
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void cboLocTrangThaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLocTrangThaiItemStateChanged
        // TODO add your handling code here:
        int trangThai = cboLocTrangThai.getSelectedIndex();
        List<HoaDon> lst = hdSer.getSearchTrangThai(trangThai);

        if (lst.size() == 0) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy");
            return;
        } else {
            loadTable(lst);
            JOptionPane.showMessageDialog(this, "Đã tìm thấy");
            return;
        }
    }//GEN-LAST:event_cboLocTrangThaiItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHienThi;
    private javax.swing.JButton btnLocDate;
    private javax.swing.JComboBox<String> cboLocTrangThai;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMauSac;
    private com.toedter.calendar.JDateChooser txtNgayThanhToan;
    private javax.swing.JTextPane txtNote;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtSoTienGiam;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtTim;
    private com.toedter.calendar.JDateChooser txtTimKiemNgay;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtXuatXu;
    // End of variables declaration//GEN-END:variables
}
